### ISSUE TITLE
Need method for BunnyCDNStorage, _http.BaseAddress

### ISSUE THREAD

**Issue by HyeokSuLee** [BunnyWay/BunnyCDN.Net.Storage#10]
In BunnyCDN.Net.Storage/BunnyCDNStorage.cs

In the Constructor of BunnyCDNStorage, it sets 
`_http.BaseAddress = new Uri("https://storage.bunnycdn.com/");`
but when i use this. The messege says it is succeeded. But Actually it doesn't.
Upload file, messege 'complete', but no file on storage.

To fix this, I have to change to local uri "https://ny.storage.bunnycdn.com".

But i don't think this is what you intend to with this library.
I don't want hackky code. So please support this issue.

Fyi. I dev on Unity3D engine.

**Comment by DejanPelzel** [comment]
Thank you for the feedback. We are planning an update to correctly support the new storage locations. It should be available in a few days.

**Comment by DejanPelzel** [comment]
This has been updated and pushed to NuGet.
