### ISSUE TITLE
NuGet availability

### ISSUE THREAD

**Issue by OhSoooLucky** [BunnyWay/BunnyCDN.Net.Storage#2]
Will this project be released on NuGet by any chance?

**Comment by DejanPelzel** [comment]
Hello,

Definitely will :)
We've just published a Nuget package with the initial release with the netstandard 2.1 version build:
https://www.nuget.org/packages/BunnyCDN.Net.Storage/

**Comment by OhSoooLucky** [comment]
Would something like continuous delivery tests & nuget upload upon git tag creation be a thing you are willing to look into?

I believe this could drastically improve progress on this project without requiring much internal work from BunnyWays, other than creating the tag.

I'd gladly add such system into my #4 PR.

**Comment by DejanPelzel** [comment]
Definitely, we're a bit busy right now but I'll try to find some time for this, perhaps once the upcoming GEO replication features are added.

**Comment by OhSoooLucky** [comment]
I'm on it
