### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rubentorresbonet** [BunnyWay/BunnyCDN.Net.Storage#5]
Hi, would you mind adding a license? A MIT license or the sort would be great. Thanks

**Comment by OhSoooLucky** [comment]
Currently it's licensed under the Apache 2.0 license over at https://www.nuget.org/packages/BunnyCDN.Net.Storage/

So it's probably going to be that.

**Comment by rubentorresbonet** [comment]
Thanks for that link.

Would it be possible to add it to a license file in this github repository?

I need to fork it to do some changes.

**Comment by DejanPelzel** [comment]
Hello,

We just added the MIT license to the project as well. Feel free to use or modify anything you want :)

**Comment by OhSoooLucky** [comment]
Shouldn't the project also have its package license set to MIT for future releases?
